### PR TITLE
Almost complete database manager

### PR DESCRIPTION
**Pull request by venkatarun95**
Things still missing:
- Function to verify all certificates
- The presence of certain state variables such as election status, no of votes/min (for shutdown of system) etc.
- Things specific to one of the other teams. In case something more than simple database access is required do let the database team know, and we'll do it for you.

PS: please do not access anything from models.py from outside of databaseManager.py. Make a small utility function there and call that. The advantages of maintaining such modularity may not be clear now, but believe me, they are tremendous when an unexpected change needs to be made.

### CODE REVIEW

**Comment by kunaaljain** [comment]
Hi, I will work on remaining functions, resolve conflicts since it says cannot be merged, and then merge it. Sounds good eh?

**Comment by alpeshvas** [comment]
hello .i made login page ..currently i call function from databsemanager LoginUser(Username,Password)  for auntheticity of user...!  what should i do ...? check aunthenticity of user by calling this function from databasemanager , or directly check from our databse(.db file) ?

**Comment by venkatarun95** [comment]
Django has its own login system. Check that out. We will not be making our own system as Django's system is quite convenient and secure.

**Comment by alpeshvas** [comment]
then what is use of function -LoginUser which is made in databasemanager.py ?

**Pull request merged**
